### PR TITLE
Core Members: Add RohanVB

### PR DESCRIPTION
**Pull request by RohanVB**
Closes https://github.com/coala/teams/issues/46

### CODE REVIEW

**Comment by RohanVB** [comment]
Note: Will add responsibilities after discussed with the team leader.

**Comment by adtac** [comment]
@RohanVB limit to 80 chars please :)

And let's discuss your responsibities!

**Comment by adtac** [comment]
And yes, I shall be addressed only as The Glorious Leader :P

**Comment by RohanVB** [comment]
>  limit to 80 chars please

will do, my bad. 

> And let's discuss your responsibities!

Well I think the projects should be aligned with my interests - a few things: I started contributing to coala since I had holidays, because of the activeness of the gitter community, which got me familiar with git, and large codebases in general, I chose to stay. A few problems I had in the beginning (which I'd like to work on now) is with getting end-users interested in using coala, which I believe can be done through plugins which are unfortunately not well maintained at the moment. The entire process would be properly documented (on making new plugins for the future), since another issue I had was with following the existing docs. I understand that the perception of the readers will differ, but a general outline should be maintained. The existing plugins should have tutorials, usage information in the README's, and as lasse mentioned, getting them automated in a repo (specific to editor plugins) which is released with every new coala version release. I mentioned a couple more points in the issue, I think most of it covers what I'd like to do, and as always, I'm open to new responsibilities and possibilities. :D

**Comment by adtac** [comment]
@RohanVB Neat. The plugins don't get enough attention, indeed,

You mentioned in your application that you want to group all plugins under one single repo. I'm not really sure how this will help - in fact, I think this will be a step backwards in terms of usability:

- `vim` has something called `Vundle` that has a super-easy install procedure. You just add `PluginInstall 'coala/coala-vim'` to your vimrc and it'll take care of the installation process. The point is, having individual repos makes it easier to install.

- If someone wants to download *just* the Sublime Text plugin, they can't. They'll need to download the entire repo.

- We're actually moving towards decentralization in coala-bears. I don't think centralization here is the best idea.

The only probably advantage a unified repo offers is in maintainability (which I don't entirely believe in). I'm just not sure it's worth the decrease in usability.

**Comment by RohanVB** [comment]
@adtac 
Valid points. I think we can separate the point we agree on and start a roadmap from there. Popularity of the editor plugins could be enhanced by other means if we aren't getting a single repo - **like having a section on coala.io highlighting the plugins** (it doesn't have a section for this I guess), and since they are separate repos, each individual one could have, as mentioned earlier, 

> existing plugins should have tutorials, usage information in the README's

also:

- documentation on creating new plugins, things that need to be kept in mind
- making sure the existing plugins work and are maintained
- making new plugins for popular editors
- other ways we can make usability of plugins easier for developers and users.

So, compiled list of responsibilities I am assigned to (so I can submit the revision of team-members.rst), glorious leader?

**Comment by sils** [comment]
Conflicts!

**Comment by RohanVB** [comment]
Yeah, I wanted to get an update from @adtac of my final list of responsibilities I could add to the .rst file. Final update so I can add them :)
Otherwise, if the details are enough as is, then it can be merged.

**Comment by sils** [comment]
ack https://github.com/coala/teams/pull/50/commits/d3af369841c0dafd52bfd81d100206890ba10e59 for now

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
ack d3af369

**Pull request merged**
