### PR TITLE
gsoc_responsibilities.md: fix typo

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Review by ksdme — CHANGES_REQUESTED** [review]
Capitalize 'f' in commit message.

**Comment by waldyrious** [comment]
@ksdme I believe that can be done at merge time: if using the "squash" or "rebase" merge options, GitHub allows tweaking the commit message. Or are there reasons that approach can't be used?

**Comment by ksdme** [comment]
The rebase and merge isn't done from command line and instead a bot is used by maintainers to handle that. You should do it locally and then push the changes. You can rebase and reword the commit message.

**Comment by waldyrious** [comment]
@ksdme ok, sure, no problem. I did the change in the GitHub web interface, but I'm comfortable making a local clone and amending the commit. But please be aware that this kind of requirement will raise the barriers for contributions from beginners, and might discourage them. Do you guys have plans to mitigate this sort of barriers? I'd be happy to help with that if I can :)

**Comment by jayvdb** [comment]
@waldyrious , we're only interested in newcomers who want to learn good practises and will follow http://coala.io/newcomer .
We're aware that this does discourage beginners, and slows down the 'quick' fix, but after a person knows the git commit message is enforced they can use GitHub UI to do quick fixes as they know how to write compliant commit messages in the web interface.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack https://github.com/coala/teams/pull/78/commits/b4ed23144cd7b2f913681f5b77569c3f9e22fd69

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by waldyrious** [comment]
> we're only interested in newcomers who want to learn good practises and will follow http://coala.io/newcomer.

Fair enough. I would love if contributions made in the spur of the moment were encouraged, as that tends to be a great way to hook people in their first steps into the world of collaborative projects. That said, I'm also aware that maintainer burnout is a more serious problem than newcomer friction, so a balance needs to be struck if there isn't a way to hand-hold contributors in a scalable manner. Hopefully more/smarter bots will help in this area moving forward.

> after a person knows the git commit message is enforced they can use GitHub UI to do quick fixes as they know how to write compliant commit messages in the web interface.

I personally don't think allowing more convenient later contributions justifies the risk of driving out complete beginners at the first one (who are arguably the ones who need a smooth contribution flow the most), but again, I respect that that decision belongs to the active project maintainers.

**Comment by virresh** [comment]
The commit should've also mentioned the corresponding issue: https://github.com/coala/teams/issues/77

Probably we need to manually close that now ?

**Comment by waldyrious** [comment]
Oh wow, I didn't realize there was an issue for that. Indeed, it must be manually closed now.

**Comment by meetmangukiya** [comment]
Closed

**Pull request merged**
