### PR TITLE
community_idea.md: Add Hemang Kumar as member

### PR DESCRIPTION
**Pull request by sims1253**

### CODE REVIEW

**Comment by sims1253** [comment]
nonononono :D

**Comment by sims1253** [comment]
Don't merge this

**Comment by sims1253** [comment]
This is blocked until @hemangsk is a developer or maintainer.

**Comment by hemangsk** [comment]
And a developer now 🎉  🎆 🍾 🎉

**Comment by Mixih** [comment]
ack 63338a1

**Comment by Mixih** [comment]
Welcome to developers @hemangsk !

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
