### PR TITLE
Core: Add Rohan, Udayan, Rishav, Asnel, and Hemang

### PR DESCRIPTION
**Pull request by adtac**

### CODE REVIEW

**Comment by sims1253** [comment]
Squash them and reference(and close) all the relevant issues?

**Comment by adtac** [comment]
All closes are in the commit messages :/ I'll help you out with the ack :P

```
<type ack here; I don't want to accidently ack it myself> https://github.com/coala/teams/pull/53/commits/144434ecb04a14a88b6fe7f4d9d17f84980b281e https://github.com/coala/teams/pull/53/commits/246f2fff86c5eb3edc4669c44a08620e94cf108e https://github.com/coala/teams/pull/53/commits/23248f4cd7b028293ed3dfc52f07985a6bb134a4 https://github.com/coala/teams/pull/53/commits/4a9f43a2b4e0fd1c24af26b5d066dfb54fe32ad0 https://github.com/coala/teams/pull/53/commits/ebaa27c257b5cabf3bd0c7d30a031984783b3ec5 https://github.com/coala/teams/pull/53/commits/c0e638a2784796b8dfb6159fce349abf93b17898 https://github.com/coala/teams/pull/53/commits/d82311a0643a3a0a4079312ef015b9b4876ae669
```

**Comment by sils** [comment]
ack
https://github.com/coala/teams/pull/53/commits/144434ecb04a14a88b6fe7f4d9d17f84980b281e https://github.com/coala/teams/pull/53/commits/246f2fff86c5eb3edc4669c44a08620e94cf108e https://github.com/coala/teams/pull/53/commits/23248f4cd7b028293ed3dfc52f07985a6bb134a4 https://github.com/coala/teams/pull/53/commits/4a9f43a2b4e0fd1c24af26b5d066dfb54fe32ad0 https://github.com/coala/teams/pull/53/commits/ebaa27c257b5cabf3bd0c7d30a031984783b3ec5 https://github.com/coala/teams/pull/53/commits/c0e638a2784796b8dfb6159fce349abf93b17898 https://github.com/coala/teams/pull/53/commits/d82311a0643a3a0a4079312ef015b9b4876ae669

**Comment by sils** [comment]
ack 144434e 246f2ff 23248f4 4a9f43a ebaa27c c0e638a d82311a

**Comment by sils** [comment]
@adtac conflicts though

**Comment by adtac** [comment]
reack https://github.com/coala/teams/pull/53/commits/f918e1e10d31c6e0e37ccc0fa60cc92461681cb2 https://github.com/coala/teams/pull/53/commits/b9781cbf7a5c107e83fdfe3650f2169ef24b986d https://github.com/coala/teams/pull/53/commits/f178e98712c696670610f8a903504c696782a210 https://github.com/coala/teams/pull/53/commits/def95dd665479d5808636fbf3f1226c289e5a56f https://github.com/coala/teams/pull/53/commits/bac4876bb24e84d10e5f1b49f65974dd74ca8a68 https://github.com/coala/teams/pull/53/commits/24e33e7574cc0bae5dca9810988dd0c5136c3ff2

**Comment by adtac** [comment]
@rultor merge

**Pull request merged**
